### ISSUE TITLE
网易云的插件希望能改进一下。

### ISSUE THREAD

**Issue by novaneo** [dingdang-robot/dingdang-contrib#31]
网易云的插件希望能改进一下。每播放一首歌之前都要说一次歌手及歌曲名，比较烦人。希望把这个烦人的部分去掉，直接播放就行了。

**Comment by wzpan** [comment]
done。在网易云音乐插件的设置里头加上 “report: false” 即会关闭播报。

```
# 网易音乐
netease_music:
    account: '您的账号' # 只支持手机账户
    password: '您的密码'
    report: true    # 是否播报即将播放的音乐
```
